const key = `CommunitiesOverview`;
const path = `src/${key}/`;

export const FLUSH_STATE = `${path}FLUSH_STATE`;

export const LOAD_MY_COMMUNITIES = `${path}LOAD_MY_COMMUNITIES`;
export const LOAD_MY_COMMUNITIES_SUCCESS = `${path}LOAD_MY_COMMUNITIES_SUCCESS`;
export const LOAD_MY_COMMUNITIES_ERROR = `${path}LOAD_MY_COMMUNITIES_ERROR`;

export const LOAD_ACTIVE_COMMUNITIES = `${path}LOAD_ACTIVE_COMMUNITIES`;
export const LOAD_ACTIVE_COMMUNITIES_SUCCESS = `${path}LOAD_ACTIVE_COMMUNITIES_SUCCESS`;
export const LOAD_ACTIVE_COMMUNITIES_ERROR = `${path}LOAD_ACTIVE_COMMUNITIES_ERROR`;

export const UPDATE_COMMUNITY_REQUEST_JOINS_BY_ID = `${path}UPDATE_COMMUNITY_REQUEST_JOINS_BY_ID`;

export const UPDATE_COMMUNITY_INVITATIONS_BY_ID = `${path}UPDATE_COMMUNITY_INVITATIONS_BY_ID`;
