/*
 *
 * Notifications constants
 *
 */

const key = `Notifications`;
const path = `src/${key}/`

export const FLUSH = `${path}FLUSH`;
export const SET_NO_MORE = `${path}SET_NO_MORE`;

export const RESET_NOTIFICATIONS = '`${path}RESET_NOTIFICATIONS`';
export const RESET_NOTIFICATIONS_SUCCESS = `${path}RESET_NOTIFICATIONS_SUCCESS`;
export const RESET_NOTIFICATIONS_ERROR = `${path}RESET_NOTIFICATIONS_ERROR`;

export const LOAD_FRESH_NOTIFICATIONS = `${path}LOAD_FRESH_NOTIFICATIONS`;
export const LOAD_FRESH_NOTIFICATIONS_SUCCESS = `${path}LOAD_FRESH_NOTIFICATIONS_SUCCESS`;
export const LOAD_FRESH_NOTIFICATIONS_ERROR = `${path}LOAD_FRESH_NOTIFICATIONS_ERROR`;

export const LOAD_NOTIFICATIONS = '`${path}LOAD_NOTIFICATIONS`';
export const LOAD_NOTIFICATIONS_SUCCESS = `${path}LOAD_NOTIFICATIONS_SUCCESS`;
export const LOAD_NOTIFICATIONS_ERROR = `${path}LOAD_NOTIFICATIONS_ERROR`;

export const UPDATE_NOTIFICATION = '`${path}UPDATE_NOTIFICATION`';
export const UPDATE_NOTIFICATION_SUCCESS = `${path}UPDATE_NOTIFICATION_SUCCESS`;
export const UPDATE_NOTIFICATION_ERROR = `${path}UPDATE_NOTIFICATION_ERROR`;


