/*
 *
 * CommunityDetail constants
 *
 */
const key = `CommunityDetail`;
const path = `src/${key}/`;

export const FLUSH_STATE = `${path}FLUSH_STATE`;

// LOAD
export const LOAD_COMMUNITYDETAIL = `${path}LOAD_COMMUNITYDETAIL`;
export const LOAD_COMMUNITYDETAIL_SUCCESS = `${path}LOAD_COMMUNITYDETAIL_SUCCESS`;
export const LOAD_COMMUNITYDETAIL_ERROR = `${path}LOAD_COMMUNITYDETAIL_ERROR`;

// CHANGE/UPDATE
export const CHANGE_COMMUNITYDETAIL = `${path}CHANGE_COMMUNITYDETAIL`;
export const CHANGE_COMMUNITYDETAIL_SUCCESS = `${path}CHANGE_COMMUNITYDETAIL_SUCCESS`;
export const CHANGE_COMMUNITYDETAIL_ERROR = `${path}CHANGE_COMMUNITYDETAIL_ERROR`;

// DELETE
export const DELETE_COMMUNITYDETAIL = `${path}DELETE_COMMUNITYDETAIL`;
export const DELETE_COMMUNITYDETAIL_SUCCESS = `${path}DELETE_COMMUNITYDETAIL_SUCCESS`;
export const DELETE_COMMUNITYDETAIL_ERROR = `${path}DELETE_COMMUNITYDETAIL_ERROR`;

// CHANGE/UPDATE Media
export const UPLOAD_MEDIA = `${path}UPLOAD_MEDIA`;
export const UPLOAD_MEDIA_SUCCESS = `${path}UPLOAD_MEDIA_SUCCESS`;
export const UPLOAD_MEDIA_ERROR = `${path}UPLOAD_MEDIA_ERROR`;

// LOAD ALL TAGS
export const LOAD_TAGS = `${path}LOAD_TAGS`;
export const LOAD_TAGS_SUCCESS = `${path}LOAD_TAGS_SUCCESS`;
export const LOAD_TAGS_ERROR = `${path}LOAD_TAGS_ERROR`;

// LOAD POOULAR TAGS
export const LOAD_COMMUNITYDETAIL_TAGS = `${path}LOAD_COMMUNITYDETAIL_TAGS`;
export const LOAD_COMMUNITYDETAIL_TAGS_SUCCESS = `${path}LOAD_COMMUNITYDETAIL_TAGS_SUCCESS`;
export const LOAD_COMMUNITYDETAIL_TAGS_ERROR = `${path}LOAD_COMMUNITYDETAIL_TAGS_ERROR`;

// LOAD FEEDS
export const LOAD_FEEDS = `${path}LOAD_FEEDS`;
export const LOAD_FEEDS_SUCCESS = `${path}LOAD_FEEDS_SUCCESS`;
export const LOAD_FEEDS_ERROR = `${path}LOAD_FEEDS_ERROR`;

// POST NEW PUBLICATION
export const POST_PUBLICATION = `${path}POST_PUBLICATION`;
export const POST_PUBLICATION_SUCCESS = `${path}POST_PUBLICATION_SUCCESS`;
export const POST_PUBLICATION_ERROR = `${path}POST_PUBLICATION_ERROR`;

export const UPDATE_LIKES = `${path}UPDATE_LIKES`;

export const REPORT_POST = `${path}REPORT_POST`;
export const REPORT_POST_SUCCESS = `${path}REPORT_POST_SUCCESS`;
export const REPORT_POST_ERROR = `${path}REPORT_POST_ERROR`;

export const SET_REPORT_POPOP = `${path}SET_REPORT_POPOP`;
